name: Build and deploy Node.js app to Azure Web App - unibridge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable pnpm BEFORE setup-node cache runs
      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
           PNPM_MINIMUM_RELEASE_AGE: "0" # Temporarily bypasses the age restriction rule
      - name: Run tests
        run: pnpm test

      # Build step (add if your project needs it)
      - name: Build project
        run: pnpm build

      # Upload only needed files (NOT entire repo)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules
            !.git
            !.github

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_766C0B717B5E4C58906E6CA5DC06E041 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45F125ED28094DA685021EA701135BED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF2C75A5A6884B5DB4DFDA93233BEE8F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "unibridge"
          slot-name: "Production"
          package: .
